[package]
name = "animeko-smtc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "AnimekoSMTC"
path = "src/main.rs"

[dependencies]
animeko-protocol.workspace = true
anyhow.workspace = true
serde_json.workspace = true
uuid = { version = "1", features = ["v4"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61", features = [
    "Foundation", "Media", "Storage_Streams",
    "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Security", "Win32_System_Com",
    "Win32_System_WinRT", "Win32_System_LibraryLoader", "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging", "Win32_UI_Shell", "Win32_UI_Controls_Dialogs",
] }
