[package]
name = "animeko-probe"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
animeko-protocol.workspace = true
serde_json.workspace = true
anyhow.workspace = true
jni = "0.21.1"

[build-dependencies]
bindgen = "0.72"
